# Assignments
https://www.machinelearningplus.com/python/101-numpy-exercises-python/
https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-150.php

In [5]:
#Desired output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

In [6]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Q. Create a 3×3 numpy array of all True’s

In [7]:
a1= np.arange(1,10,1)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a2 = np.full((3,3),True,dtype='bool')
a2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [21]:
#Q. Extract all odd numbers from arr

#Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#> array([1, 3, 5, 7, 9])

In [32]:
print(arr[arr % 2 ==1])

[1 3 5 7 9]


In [ ]:
#Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Desired Output: Replace all odd numbers in arr with -1

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [36]:
arr[arr %2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
#Q. Replace all odd numbers in arr with -1 without changing arr

#Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Desired Output:

#out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1 = arr.copy()
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr1[arr % 2 ==1] = -1
print('modified array',arr1)
print('original array',arr)

modified array [ 0 -1  2 -1  4 -1  6 -1  8 -1]
original array [0 1 2 3 4 5 6 7 8 9]


In [48]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr) # where condition
print(arr)
out


[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:


#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [50]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
#Q. Stack arrays a and b vertically Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])


In [65]:
print(a)
print('-------------')
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [68]:
np.vstack([a,b])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [69]:
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3: https://numpy.org/doc/stable/reference/generated/numpy.r_.html
np.r_[a, b]
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [71]:
#Q. Stack the arrays a and b horizontally.

#Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [72]:
print(a)
print('-------------')
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
-------------
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [74]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [77]:
np.concatenate([a,b], axis= 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [78]:
# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [83]:
#Input: Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
a
#Desired Output:

#  array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

array([1, 2, 3])

In [99]:
a1= np.full((1,3),1)
print(a1)
a2= np.full((1,3),2)
print(a2)
a3= np.full((1,3),3)
print(a3)

[[1 1 1]]
[[2 2 2]]
[[3 3 3]]


In [95]:
r1 = np.hstack([a1,a2,a3])
r =  np.hstack([a,a,a])

print(r)
print(r1)

[1 2 3 1 2 3 1 2 3]
[[1 1 1 2 2 2 3 3 3]]


In [104]:
print(r.ndim)
print(r1.ndim)
print(r1.reshape(-1)) # reduce the dimension of th
print((r1.reshape(-1)).ndim) # reduce the dimension of the array 

1
2
[1 1 1 2 2 2 3 3 3]
1


In [106]:
r1 = r1.reshape(-1)
print(r.ndim)
print(r1.ndim)

1
1


In [109]:
print(a)
np.r_[np.repeat(a, 3), np.tile(a, 3)]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [112]:
x = np.array([3, 5, 7])
print(x)
print('--------------------')
print(np.tile(x, 3))
print('--------------------')
print(np.tile(x, (3,3)))

[3 5 7]
--------------------
[3 5 7 3 5 7 3 5 7]
--------------------
[[3 5 7 3 5 7 3 5 7]
 [3 5 7 3 5 7 3 5 7]
 [3 5 7 3 5 7 3 5 7]]


In [115]:
y = np.array([[3, 4], [5, 6]])
print(y)
print('--------------------')
print(np.tile(y, 3))

[[3 4]
 [5 6]]
--------------------
[[3 4 3 4 3 4]
 [5 6 5 6 5 6]]


In [107]:
np_array_2d = np.array([[6,7],[8,9]]) 
print(np_array_2d)
print('--------------------')
print(np.repeat(np_array_2d,2,axis=0))
print('--------------------')
print(np.repeat(np_array_2d,2,axis=1))

[[6 7]
 [8 9]]
--------------------
[[6 7]
 [6 7]
 [8 9]
 [8 9]]
--------------------
[[6 6 7 7]
 [8 8 9 9]]


In [117]:
#Q. Get the common items between a and b

#Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Desired Output:

#array([2, 4])

In [119]:
np.intersect1d(a,b)

array([2, 4])

In [120]:
#Q. From array a remove all items present in array b

#Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [122]:
#Q. Get the positions where elements of a and b match

#Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [124]:
#Q. Get all items between 5 and 10 from a.

#Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])
#Desired Output:

#(array([6, 9, 10]),)

In [126]:
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [131]:
a[(a>= 5) & (a<= 10)]

array([ 6,  9, 10])

In [132]:
# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [133]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

In [167]:
#Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [159]:
c1 = arr[:,0]
c1

array([0, 3, 6])

In [151]:
c2 = arr[:,1]
c2

array([1, 4, 7])

In [168]:
x= arr[:,[0,1]] = arr[:,[1,0]]
arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [162]:

my_array = np.arange(12).reshape(3, 4)
print("Original array:")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("\nAfter swapping arrays:")
print(my_array)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

After swapping arrays:
[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]


In [171]:
A= np.array([[ 0., -1.,  0.,  0.],
       [ 0.,  1.,  1.,  1.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])
#This is an elegant way to swap the columns:

A.T[[0, 1]] = A.T[[1, 0]]  # swap the first two columns
A

array([[-1.,  0.,  0.,  0.],
       [ 1.,  0.,  1.,  1.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])