#     Numpy basics


In [3]:
import numpy as np

In [4]:
list = [1,'two', 7,5.0]

In [9]:
type(list)

list

In [5]:
npa = np.array(list)
npa

array(['1', 'two', '7', '5.0'], dtype='<U11')

In [8]:
type(npa)

numpy.ndarray

In [11]:
npa.shape 

(4,)

In [7]:
npa = np.append(npa,[11])
print(npa)

['1' 'two' '7' '5.0' '11']


In [8]:
np.insert(npa,0,'66')

array(['66', '1', 'two', '7', '5.0', '11'], dtype='<U11')

In [9]:
list1 = [1,3,5]
list2 = [2,4,6]
list1 + list2

[1, 3, 5, 2, 4, 6]

In [33]:
list + [20]

[1, 'two', 7, 5.0, 20]

In [10]:
npa = np.array(list1+ list2)
npa

array([1, 3, 5, 2, 4, 6])

In [31]:
npa = npa + 0
npa

array([1, 3, 5, 2, 4, 6])

In [11]:
list_sublist = [[1,2],[3,4],[5,6]] 
list_sublist

[[1, 2], [3, 4], [5, 6]]

In [12]:
npa_2d = np.array(list_sublist)
npa_2d 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
npa_2d.shape

(3, 2)

In [38]:
npa_2d = np.array(list_sublist, dtype='float')
npa_2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [39]:
npa_2d.astype(int)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
npa_2d = npa_2d.astype('str') 
npa_2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [15]:
npa_2d[0][0]

1

In [14]:
npa_2d[0][0] + str('7')

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [16]:
str(1.0)+'2.3'

'1.02.3'

In [52]:
# np.nan , np.inf

In [53]:
np.NaN


nan

In [55]:
np.nan

nan

In [56]:
np.NaN == np.NaN

False

In [57]:
np.inf

inf

In [58]:
np.inf == np.inf

True

In [60]:
None == None 

True

In [61]:
npa_2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['5.0', '6.0']], dtype='<U32')

In [17]:
npa_2d = npa_2d.astype('int32')

In [63]:
npa_2d = npa_2d.astype('float')
npa_2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [64]:
npa_2d = npa_2d.astype('int')
npa_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
npa_2d = npa_2d.astype('float')
npa_2d

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [66]:
npa_2d[0,1]

2.0

In [67]:
npa_2d[0,1] = np.nan
npa_2d[1,1] = np.inf
npa_2d

array([[ 1., nan],
       [ 3., inf],
       [ 5.,  6.]])

In [68]:
np.isinf(npa_2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [71]:
np.isnan(npa_2d)

array([[False,  True],
       [False, False],
       [False, False]])

In [72]:
npa_2d != np.isnan(npa_2d)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [74]:
flag = np.isinf(npa_2d) | np.isnan(npa_2d)
flag

array([[False,  True],
       [False,  True],
       [False, False]])

In [75]:
npa_2d[flag]

array([nan, inf])

In [76]:
npa_2d[flag] = 0
npa_2d

array([[1., 0.],
       [3., 0.],
       [5., 6.]])

# Statistical Operations 
#mean, meidian , mode ,max,min 

In [25]:
npa_2d.astype('int')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
npa_2d.max()

6

In [27]:
npa_2d.mean()

3.5

In [28]:
npa_2d.mean(axis=1)

array([1.5, 3.5, 5.5])

In [29]:
npa_2d.mean(axis=0)

array([3., 4.])

In [30]:
npa_2d.sum()

21

In [31]:
npa_2d.var() # variance

2.9166666666666665

In [32]:
npa_2d.std() # std deviation

1.707825127659933

In [33]:
np.median(npa_2d) # median 

3.5

In [34]:
from scipy import stats
stats.mode(npa_2d,axis=0)

ModeResult(mode=array([[1, 2]]), count=array([[1, 1]]))

# Shape() , Reshape(), Ravel()

In [35]:
npa_2d.shape

(3, 2)

In [37]:
npa_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
npa_2d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
npa_2d.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [43]:
npa_2d.ravel() # 2 dimensionqal array changed to 1 dimensional array


array([1, 2, 3, 4, 5, 6])

In [44]:
npa_2d.flatten()

array([1, 2, 3, 4, 5, 6])

# Sequence , Repetitions ,Random numbers 

In [45]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.arange(1,11,2,dtype='int')

array([1, 3, 5, 7, 9])

In [ ]:
np.arange() # Shift + double Tab gives functin defination 

In [57]:
np.linspace(0,100,4,dtype='int')

array([  0,  33,  66, 100])

In [62]:
np.logspace(1,100,10,dtype='int')

array([         10, -2147483648, -2147483648, -2147483648, -2147483648,
       -2147483648, -2147483648, -2147483648, -2147483648, -2147483648])

In [65]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.zeros([1,3])

array([[0., 0., 0.]])

In [67]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones([1,5])

array([[1., 1., 1., 1., 1.]])

In [70]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.tile() # Repeat 

In [77]:
#Examples
#--------
a = np.array([0, 1, 2])
np.tile(a, 2)



array([0, 1, 2, 0, 1, 2])

In [79]:
np.tile(a, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [80]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [81]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [82]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [84]:
c = np.array([1,2,3,4])
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [88]:
np.repeat(3, 4) # Repeat on each element of array 

array([3, 3, 3, 3])

In [87]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [89]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [90]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [91]:
np.random.rand(3,3)

array([[0.82365228, 0.61587929, 0.06689338],
       [0.79448865, 0.35413913, 0.26826891],
       [0.78765297, 0.76204451, 0.86387449]])

In [99]:
np.random.randint(0,10,(3,3))

array([[9, 1, 3],
       [8, 0, 6],
       [5, 8, 5]])

In [107]:
np.random.seed(1) # fixing the randwom number 
np.random.randint(0,10,(3,3))

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [118]:
np.unique(np.random.randint(0,10,(3,3)))

array([2, 4, 5, 6, 7, 8])

In [119]:
np.unique(['a', 'b', 'b', 'c', 'a'],return_counts= True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

# Where 

In [143]:
goodvalues = [3, 4, 7]
ix = np.isin(x, goodvalues)
print (x)
print('+++++++')
print(ix)
print('+++++++')
print(np.where(ix))


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
+++++++
[[False False False]
 [ True  True False]
 [False  True False]]
+++++++
(array([1, 1, 2], dtype=int64), array([0, 1, 1], dtype=int64))


In [155]:
print(x)


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [147]:
arr = np.array([4,10,24,4,11,17,40,99])
arr


array([ 4, 10, 24,  4, 11, 17, 40, 99])

In [156]:
np.where(arr > 20)


(array([2, 6, 7], dtype=int64),)

In [157]:
index = np.where(arr > 20 )
arr[index]

array([24, 40, 99])

In [158]:
arr >20

array([False, False,  True, False, False, False,  True,  True])

In [159]:
arr[arr >20]

array([24, 40, 99])

In [160]:
arr.argmax()

7

In [161]:
arr.argmin()

0

# File Read Write 

In [162]:
npa_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [163]:
np.savetxt("npa2D.csv",npa_2d,delimiter=',')

In [164]:
np.loadtxt("npa2D.csv", delimiter=',')

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [167]:
np.savez('merged.csv',npa,npa_2d)

In [171]:
d= np.load('merged.csv.npz')
d.files

['arr_0', 'arr_1']

In [173]:
d[d.files[0]]

array([1, 3, 5, 2, 4, 6])

In [174]:
d[d.files[1]]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [176]:
np.concatenate([npa,npa])

array([1, 3, 5, 2, 4, 6, 1, 3, 5, 2, 4, 6])

In [178]:
np.concatenate([npa_2d,npa_2d],axis =0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [179]:
np.concatenate([npa_2d,npa_2d],axis =1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [180]:
np.vstack([npa_2d,npa_2d])

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [183]:
np.hstack([npa_2d,npa_2d])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

In [184]:
npa_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [186]:
npa_2d[0,0]= 4

In [187]:
npa_2d

array([[4, 2],
       [3, 4],
       [5, 6]])

In [191]:
npa_2d.sort()
npa_2d

array([[2, 4],
       [3, 4],
       [5, 6]])

# DateTime 

In [ ]:
#https://blog.finxter.com/how-to-work-with-dates-and-times-in-python/

In [195]:
d= np.datetime64("2020-12-01 20:00:00")
d

numpy.datetime64('2020-12-01T20:00:00')

In [196]:
# second addition 
d+ 10 

numpy.datetime64('2020-12-01T20:00:10')

In [197]:
#add day 
oneDay = np.timedelta64(1,'D')
oneDay

numpy.timedelta64(1,'D')

In [200]:
d+ oneDay

numpy.datetime64('2020-12-02T20:00:00')

In [ ]:
oneMinute = np.timedelta64()